#!/usr/bin/env python3
"""
Playwright ScriptForge CLI
Non-interactive CLI for recording, converting, and compiling Playwright scripts
"""
import click
import yaml
import os
import sys
import subprocess
from pathlib import Path
from python_to_yaml import python_to_yaml_dict
from yaml_to_python import compile_yaml_to_python


@click.group()
@click.version_option(version='1.0.0')
def cli():
    """
    Playwright ScriptForge - Round-trip automation workflow tool
    
    Record Playwright sessions, convert to editable YAML, and compile back to Python.
    """
    pass


@cli.command()
@click.option('--url', required=True, help='Starting URL for recording')
@click.option('--output', '-o', default='script.py', help='Output Python file path')
@click.option('--browser', default='chromium', type=click.Choice(['chromium', 'firefox', 'webkit']), 
              help='Browser to use for recording')
@click.option('--headless/--headed', default=False, help='Run in headless mode')
def record(url, output, browser, headless):
    """
    Record a Playwright session using codegen
    
    Launches Playwright codegen in non-interactive mode to record actions.
    The generated Python code is saved to the specified output file.
    """
    click.echo(f"🎬 Recording Playwright session...")
    click.echo(f"   URL: {url}")
    click.echo(f"   Browser: {browser}")
    click.echo(f"   Output: {output}")
    
    # Build codegen command
    cmd = ['playwright', 'codegen', url, '--target', 'python']
    cmd.extend(['--browser', browser])
    
    if headless:
        cmd.append('--headless')
    
    # Output file
    cmd.extend(['--output', output])
    
    try:
        # Run codegen with explicit shell=False for security
        result = subprocess.run(cmd, capture_output=True, text=True, shell=False, timeout=300)
        
        if result.returncode == 0:
            click.echo(f"✅ Recording saved to: {output}")
            click.echo(f"\nNext step: Convert to YAML with 'scriptforge convert {output}'")
        else:
            click.echo(f"❌ Recording failed: {result.stderr}", err=True)
            sys.exit(1)
            
    except FileNotFoundError:
        click.echo("❌ Playwright not found. Ensure it's installed: pip install playwright", err=True)
        sys.exit(1)
    except Exception as e:
        click.echo(f"❌ Error during recording: {e}", err=True)
        sys.exit(1)


@cli.command()
@click.argument('python_file', type=click.Path(exists=True))
@click.option('--output', '-o', help='Output YAML file path (default: <input>.yaml)')
def convert(python_file, output):
    """
    Convert Playwright Python code to YAML script
    
    Takes Python code generated by Playwright codegen and converts it to a
    YAML script with parameterized inputs for easy editing.
    """
    click.echo(f"🔄 Converting Python to YAML...")
    click.echo(f"   Input: {python_file}")
    
    # Determine output path
    if not output:
        output = Path(python_file).with_suffix('.yaml')
    
    try:
        # Read Python file
        with open(python_file, 'r') as f:
            python_code = f.read()
        
        # Convert to YAML
        yaml_dict = python_to_yaml_dict(python_code)
        
        # Write YAML file
        with open(output, 'w') as f:
            yaml.dump(yaml_dict, f, default_flow_style=False, sort_keys=False)
        
        click.echo(f"✅ YAML script saved to: {output}")
        click.echo(f"\nParameters found:")
        for param, value in yaml_dict.get('parameters', {}).items():
            click.echo(f"   {param}: {value}")
        
        click.echo(f"\nNext step: Edit parameters in {output}, then compile with 'scriptforge compile {output}'")
        
    except Exception as e:
        click.echo(f"❌ Conversion failed: {e}", err=True)
        sys.exit(1)


@cli.command()
@click.argument('yaml_file', type=click.Path(exists=True))
@click.option('--output', '-o', help='Output Python file path (default: <input>.py)')
@click.option('--param', '-p', multiple=True, help='Override parameter: -p key=value')
def compile(yaml_file, output, param):
    """
    Compile YAML script to executable Python code
    
    Takes a YAML script with parameters and generates executable Playwright
    Python code. Parameters can be overridden via command line.
    """
    click.echo(f"⚙️  Compiling YAML to Python...")
    click.echo(f"   Input: {yaml_file}")
    
    # Determine output path
    if not output:
        output = Path(yaml_file).with_suffix('.py')
    
    try:
        # Read YAML file
        with open(yaml_file, 'r') as f:
            yaml_dict = yaml.safe_load(f)
        
        # Parse parameter overrides
        param_overrides = {}
        for p in param:
            if '=' in p:
                key, value = p.split('=', 1)
                param_overrides[key] = value
        
        # Merge parameter overrides
        if param_overrides:
            if 'parameters' not in yaml_dict:
                yaml_dict['parameters'] = {}
            yaml_dict['parameters'].update(param_overrides)
            click.echo(f"\nParameter overrides:")
            for key, value in param_overrides.items():
                click.echo(f"   {key}: {value}")
        
        # Compile to Python
        python_code = compile_yaml_to_python(yaml_dict)
        
        # Write Python file
        with open(output, 'w') as f:
            f.write(python_code)
        
        # Make executable
        os.chmod(output, 0o755)
        
        click.echo(f"✅ Python script saved to: {output}")
        click.echo(f"\nNext step: Run the script with 'python {output}'")
        
    except Exception as e:
        click.echo(f"❌ Compilation failed: {e}", err=True)
        sys.exit(1)


@cli.command()
@click.argument('yaml_file', type=click.Path(exists=True))
def validate(yaml_file):
    """
    Validate YAML script syntax and structure
    
    Checks if the YAML script is properly formatted and contains required fields.
    """
    click.echo(f"🔍 Validating YAML script...")
    click.echo(f"   File: {yaml_file}")
    
    try:
        # Read and parse YAML
        with open(yaml_file, 'r') as f:
            yaml_dict = yaml.safe_load(f)
        
        # Validate structure
        errors = []
        
        if not isinstance(yaml_dict, dict):
            errors.append("YAML must be a dictionary")
        
        if 'actions' not in yaml_dict:
            errors.append("Missing required field: 'actions'")
        elif not isinstance(yaml_dict['actions'], list):
            errors.append("'actions' must be a list")
        
        if errors:
            click.echo("❌ Validation failed:")
            for error in errors:
                click.echo(f"   - {error}")
            sys.exit(1)
        
        # Validate actions
        action_count = len(yaml_dict['actions'])
        click.echo(f"\n✅ YAML is valid!")
        click.echo(f"   Actions: {action_count}")
        click.echo(f"   Parameters: {len(yaml_dict.get('parameters', {}))}")
        
        # Show action summary
        if action_count > 0:
            click.echo("\nAction summary:")
            for idx, action in enumerate(yaml_dict['actions'], 1):
                action_type = action.get('action', 'unknown')
                click.echo(f"   {idx}. {action_type}")
        
    except yaml.YAMLError as e:
        click.echo(f"❌ YAML syntax error: {e}", err=True)
        sys.exit(1)
    except Exception as e:
        click.echo(f"❌ Validation failed: {e}", err=True)
        sys.exit(1)


@cli.command()
def version():
    """Show version information"""
    click.echo("Playwright ScriptForge v1.0.0")
    click.echo("Round-trip automation workflow for Playwright")


if __name__ == '__main__':
    cli()
